[2025-05-23T10:04:51.778+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T10:04:51.790+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-23T10:04:50.562209+00:00 [queued]>
[2025-05-23T10:04:51.795+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-23T10:04:50.562209+00:00 [queued]>
[2025-05-23T10:04:51.796+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-23T10:04:51.805+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_links_task> on 2025-05-23 10:04:50.562209+00:00
[2025-05-23T10:04:51.808+0000] {standard_task_runner.py:72} INFO - Started process 61 to run task
[2025-05-23T10:04:51.811+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'get_links_task', 'manual__2025-05-23T10:04:50.562209+00:00', '--job-id', '6681', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmpopmtbpvj']
[2025-05-23T10:04:51.813+0000] {standard_task_runner.py:105} INFO - Job 6681: Subtask get_links_task
[2025-05-23T10:04:51.851+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-23T10:04:50.562209+00:00 [running]> on host f78d824d0612
[2025-05-23T10:04:51.939+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='get_links_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T10:04:50.562209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T10:04:50.562209+00:00'
[2025-05-23T10:04:51.940+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-23T10:05:57.147+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-23T10:05:57.148+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-23T10:05:57.149+0000] {process_utils.py:132} INFO - Sending 15 to group 61. PIDs of all processes in the group: [64, 76, 83, 84, 112, 120, 159, 160, 194, 61]
[2025-05-23T10:05:57.149+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 61
[2025-05-23T10:05:57.149+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-23T10:05:57.164+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=194, status='terminated', started='10:04:53') (194) terminated with exit code None
[2025-05-23T10:05:57.164+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=159, status='terminated', started='10:04:53') (159) terminated with exit code None
[2025-05-23T10:05:57.164+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=120, status='terminated', started='10:04:52') (120) terminated with exit code None
[2025-05-23T10:05:57.193+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=83, status='terminated', started='10:04:52') (83) terminated with exit code None
[2025-05-23T10:05:57.193+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=84, status='terminated', started='10:04:52') (84) terminated with exit code None
[2025-05-23T10:05:57.193+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=112, status='terminated', started='10:04:52') (112) terminated with exit code None
[2025-05-23T10:05:57.201+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76, status='terminated', started='10:04:52') (76) terminated with exit code None
[2025-05-23T10:05:57.340+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=160, status='terminated', started='10:04:53') (160) terminated with exit code None
[2025-05-23T10:06:52.149+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=64, name='node', status='sleeping', started='10:04:51') did not respond to SIGTERM. Trying SIGKILL
[2025-05-23T10:06:52.149+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=61, name='airflow task ru', status='sleeping', started='10:04:51') did not respond to SIGTERM. Trying SIGKILL
[2025-05-23T10:06:52.150+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 61
[2025-05-23T10:06:52.164+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=61, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='10:04:51') (61) terminated with exit code -9
[2025-05-23T10:06:52.165+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=64, name='node', status='terminated', started='10:04:51') (64) terminated with exit code None
[2025-05-23T10:06:52.165+0000] {standard_task_runner.py:190} ERROR - ('Job 6681 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
