[2025-05-08T03:16:38.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T03:16:38.814+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T03:16:28.316673+00:00 [queued]>
[2025-05-08T03:16:38.819+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T03:16:28.316673+00:00 [queued]>
[2025-05-08T03:16:38.819+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-08T03:16:38.829+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): ins_videos_scraper> on 2025-05-08 03:16:28.316673+00:00
[2025-05-08T03:16:38.832+0000] {standard_task_runner.py:72} INFO - Started process 193 to run task
[2025-05-08T03:16:38.835+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'instagram_videos_scraper_dag', 'ins_videos_scraper', 'manual__2025-05-08T03:16:28.316673+00:00', '--job-id', '4924', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp878mdr9q']
[2025-05-08T03:16:38.837+0000] {standard_task_runner.py:105} INFO - Job 4924: Subtask ins_videos_scraper
[2025-05-08T03:16:38.872+0000] {task_command.py:467} INFO - Running <TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T03:16:28.316673+00:00 [running]> on host 3e078d9290a5
[2025-05-08T03:16:46.576+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='instagram_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='ins_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T03:16:28.316673+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T03:16:28.316673+00:00'
[2025-05-08T03:16:46.577+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-08T03:17:03.715+0000] {selenium_manager.py:133} WARNING - The chromedriver version (136.0.7103.59) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.92); currently, chromedriver 136.0.7103.92 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[2025-05-08T03:20:02.168+0000] {job.py:229} INFO - Heartbeat recovered after 12.94 seconds
[2025-05-08T03:26:13.083+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 19, in __init__
    self._driver.add_cookie(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
from no such execution context: frame does not have execution context
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x55c80d38da8e <unknown>
#1 0x55c80ce4ab0b <unknown>
#2 0x55c80ce3b580 <unknown>
#3 0x55c80ce50b24 <unknown>
#4 0x55c80ce53e1b <unknown>
#5 0x55c80ce53ee1 <unknown>
#6 0x55c80cee2233 <unknown>
#7 0x55c80ceef618 <unknown>
#8 0x55c80cebec02 <unknown>
#9 0x55c80cedfdc5 <unknown>
#10 0x55c80cebe9b3 <unknown>
#11 0x55c80ce88c59 <unknown>
#12 0x55c80ce89a08 <unknown>
#13 0x55c80d35a40a <unknown>
#14 0x55c80d35d85e <unknown>
#15 0x55c80d35d308 <unknown>
#16 0x55c80d35dce5 <unknown>
#17 0x55c80d343b7b <unknown>
#18 0x55c80d35e050 <unknown>
#19 0x55c80d32cae9 <unknown>
#20 0x55c80d37cdf5 <unknown>
#21 0x55c80d37cfdb <unknown>
#22 0x55c80d38cc05 <unknown>
#23 0x7fda830d8134 <unknown>

[2025-05-08T03:26:13.097+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=instagram_videos_scraper_dag, task_id=ins_videos_scraper, run_id=manual__2025-05-08T03:16:28.316673+00:00, execution_date=20250508T031628, start_date=20250508T031638, end_date=20250508T032613
[2025-05-08T03:26:13.115+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-08T03:26:13.115+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4924 for task ins_videos_scraper (Message: timeout
from no such execution context: frame does not have execution context
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x55c80d38da8e <unknown>
#1 0x55c80ce4ab0b <unknown>
#2 0x55c80ce3b580 <unknown>
#3 0x55c80ce50b24 <unknown>
#4 0x55c80ce53e1b <unknown>
#5 0x55c80ce53ee1 <unknown>
#6 0x55c80cee2233 <unknown>
#7 0x55c80ceef618 <unknown>
#8 0x55c80cebec02 <unknown>
#9 0x55c80cedfdc5 <unknown>
#10 0x55c80cebe9b3 <unknown>
#11 0x55c80ce88c59 <unknown>
#12 0x55c80ce89a08 <unknown>
#13 0x55c80d35a40a <unknown>
#14 0x55c80d35d85e <unknown>
#15 0x55c80d35d308 <unknown>
#16 0x55c80d35dce5 <unknown>
#17 0x55c80d343b7b <unknown>
#18 0x55c80d35e050 <unknown>
#19 0x55c80d32cae9 <unknown>
#20 0x55c80d37cdf5 <unknown>
#21 0x55c80d37cfdb <unknown>
#22 0x55c80d38cc05 <unknown>
#23 0x7fda830d8134 <unknown>
; 193)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 19, in __init__
    self._driver.add_cookie(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
from no such execution context: frame does not have execution context
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x55c80d38da8e <unknown>
#1 0x55c80ce4ab0b <unknown>
#2 0x55c80ce3b580 <unknown>
#3 0x55c80ce50b24 <unknown>
#4 0x55c80ce53e1b <unknown>
#5 0x55c80ce53ee1 <unknown>
#6 0x55c80cee2233 <unknown>
#7 0x55c80ceef618 <unknown>
#8 0x55c80cebec02 <unknown>
#9 0x55c80cedfdc5 <unknown>
#10 0x55c80cebe9b3 <unknown>
#11 0x55c80ce88c59 <unknown>
#12 0x55c80ce89a08 <unknown>
#13 0x55c80d35a40a <unknown>
#14 0x55c80d35d85e <unknown>
#15 0x55c80d35d308 <unknown>
#16 0x55c80d35dce5 <unknown>
#17 0x55c80d343b7b <unknown>
#18 0x55c80d35e050 <unknown>
#19 0x55c80d32cae9 <unknown>
#20 0x55c80d37cdf5 <unknown>
#21 0x55c80d37cfdb <unknown>
#22 0x55c80d38cc05 <unknown>
#23 0x7fda830d8134 <unknown>

[2025-05-08T03:26:13.139+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-08T03:26:13.152+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T03:26:13.154+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
