[2025-05-16T08:11:13.285+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-16T08:11:13.298+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-16T08:11:12.255623+00:00 [queued]>
[2025-05-16T08:11:13.303+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-16T08:11:12.255623+00:00 [queued]>
[2025-05-16T08:11:13.303+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-16T08:11:13.310+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): tiktok_videos_scraper_task> on 2025-05-16 08:11:12.255623+00:00
[2025-05-16T08:11:13.313+0000] {standard_task_runner.py:72} INFO - Started process 19620 to run task
[2025-05-16T08:11:13.316+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'tiktok_videos_scraper_task', 'manual__2025-05-16T08:11:12.255623+00:00', '--job-id', '6120', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmps_f4noai']
[2025-05-16T08:11:13.317+0000] {standard_task_runner.py:105} INFO - Job 6120: Subtask tiktok_videos_scraper_task
[2025-05-16T08:11:13.353+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-16T08:11:12.255623+00:00 [running]> on host 8579eb2523da
[2025-05-16T08:11:13.404+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='tiktok_videos_scraper_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T08:11:12.255623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T08:11:12.255623+00:00'
[2025-05-16T08:11:13.404+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-16T08:11:38.598+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-16T08:11:38.599+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-16T08:11:38.600+0000] {process_utils.py:132} INFO - Sending 15 to group 19620. PIDs of all processes in the group: [19623, 19635, 19642, 19643, 19671, 19786, 19680, 19732, 19733, 19760, 19620]
[2025-05-16T08:11:38.600+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 19620
[2025-05-16T08:11:38.600+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-16T08:11:38.696+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19635, status='terminated', started='08:11:13') (19635) terminated with exit code None
[2025-05-16T08:11:38.696+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19786, status='terminated', started='08:11:16') (19786) terminated with exit code None
[2025-05-16T08:11:38.696+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19733, status='terminated', started='08:11:14') (19733) terminated with exit code None
[2025-05-16T08:11:38.696+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19642, status='terminated', started='08:11:13') (19642) terminated with exit code None
[2025-05-16T08:11:38.791+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19680, status='terminated', started='08:11:13') (19680) terminated with exit code None
[2025-05-16T08:11:38.792+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19643, status='terminated', started='08:11:13') (19643) terminated with exit code None
[2025-05-16T08:11:38.792+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19671, status='terminated', started='08:11:13') (19671) terminated with exit code None
[2025-05-16T08:11:38.891+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19732, status='terminated', started='08:11:14') (19732) terminated with exit code None
[2025-05-16T08:11:38.892+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19760, status='terminated', started='08:11:14') (19760) terminated with exit code None
[2025-05-16T08:12:33.624+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=19620, name='airflow task ru', status='sleeping', started='08:11:12') did not respond to SIGTERM. Trying SIGKILL
[2025-05-16T08:12:33.626+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=19623, name='node', status='sleeping', started='08:11:13') did not respond to SIGTERM. Trying SIGKILL
[2025-05-16T08:12:33.626+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 19620
[2025-05-16T08:12:33.641+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19620, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='08:11:12') (19620) terminated with exit code -9
[2025-05-16T08:12:33.641+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19623, name='node', status='terminated', started='08:11:13') (19623) terminated with exit code None
[2025-05-16T08:12:33.642+0000] {standard_task_runner.py:190} ERROR - ('Job 6120 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
