[2025-05-09T08:34:17.272+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-09T08:34:17.284+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: facebook_videos_scraper_dag.fb_videos_scraper manual__2025-05-09T08:34:16.570390+00:00 [queued]>
[2025-05-09T08:34:17.289+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: facebook_videos_scraper_dag.fb_videos_scraper manual__2025-05-09T08:34:16.570390+00:00 [queued]>
[2025-05-09T08:34:17.289+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-09T08:34:17.298+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): fb_videos_scraper> on 2025-05-09 08:34:16.570390+00:00
[2025-05-09T08:34:17.302+0000] {standard_task_runner.py:72} INFO - Started process 519 to run task
[2025-05-09T08:34:17.306+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'facebook_videos_scraper_dag', 'fb_videos_scraper', 'manual__2025-05-09T08:34:16.570390+00:00', '--job-id', '5176', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpj_8c7h0a']
[2025-05-09T08:34:17.307+0000] {standard_task_runner.py:105} INFO - Job 5176: Subtask fb_videos_scraper
[2025-05-09T08:34:17.349+0000] {task_command.py:467} INFO - Running <TaskInstance: facebook_videos_scraper_dag.fb_videos_scraper manual__2025-05-09T08:34:16.570390+00:00 [running]> on host af64b713d86c
[2025-05-09T08:34:17.409+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='facebook_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='fb_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T08:34:16.570390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T08:34:16.570390+00:00'
[2025-05-09T08:34:17.410+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-09T08:34:17.436+0000] {selenium_manager.py:133} WARNING - The chromedriver version (136.0.7103.59) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.92); currently, chromedriver 136.0.7103.92 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[2025-05-09T08:38:53.182+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/fb_videos_scraper.py", line 11, in fb_videos_scraper
    videos_scraper = AccountVideo(id)
  File "/opt/airflow/dags/utils/account_videos.py", line 22, in __init__
    super().__init__(user_id, base_url=f"https://www.facebook.com/{user_id}/videos")
  File "/opt/airflow/dags/utils/facebook_base.py", line 28, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x5645f5018a8e <unknown>
#1 0x5645f4ad5b0b <unknown>
#2 0x5645f4ac1306 <unknown>
#3 0x5645f4ac10bc <unknown>
#4 0x5645f4abf608 <unknown>
#5 0x5645f4abfab9 <unknown>
#6 0x5645f4acd160 <unknown>
#7 0x5645f4ae34ff <unknown>
#8 0x5645f4ae8a4b <unknown>
#9 0x5645f4ac002d <unknown>
#10 0x5645f4ae32f7 <unknown>
#11 0x5645f4b6acf7 <unknown>
#12 0x5645f4b499b3 <unknown>
#13 0x5645f4b13c59 <unknown>
#14 0x5645f4b14a08 <unknown>
#15 0x5645f4fe540a <unknown>
#16 0x5645f4fe885e <unknown>
#17 0x5645f4fe8308 <unknown>
#18 0x5645f4fe8ce5 <unknown>
#19 0x5645f4fceb7b <unknown>
#20 0x5645f4fe9050 <unknown>
#21 0x5645f4fb7ae9 <unknown>
#22 0x5645f5007df5 <unknown>
#23 0x5645f5007fdb <unknown>
#24 0x5645f5017c05 <unknown>
#25 0x7f0355d9e134 <unknown>

[2025-05-09T08:38:53.195+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=facebook_videos_scraper_dag, task_id=fb_videos_scraper, run_id=manual__2025-05-09T08:34:16.570390+00:00, execution_date=20250509T083416, start_date=20250509T083417, end_date=20250509T083853
[2025-05-09T08:38:53.210+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-09T08:38:53.210+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5176 for task fb_videos_scraper (Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x5645f5018a8e <unknown>
#1 0x5645f4ad5b0b <unknown>
#2 0x5645f4ac1306 <unknown>
#3 0x5645f4ac10bc <unknown>
#4 0x5645f4abf608 <unknown>
#5 0x5645f4abfab9 <unknown>
#6 0x5645f4acd160 <unknown>
#7 0x5645f4ae34ff <unknown>
#8 0x5645f4ae8a4b <unknown>
#9 0x5645f4ac002d <unknown>
#10 0x5645f4ae32f7 <unknown>
#11 0x5645f4b6acf7 <unknown>
#12 0x5645f4b499b3 <unknown>
#13 0x5645f4b13c59 <unknown>
#14 0x5645f4b14a08 <unknown>
#15 0x5645f4fe540a <unknown>
#16 0x5645f4fe885e <unknown>
#17 0x5645f4fe8308 <unknown>
#18 0x5645f4fe8ce5 <unknown>
#19 0x5645f4fceb7b <unknown>
#20 0x5645f4fe9050 <unknown>
#21 0x5645f4fb7ae9 <unknown>
#22 0x5645f5007df5 <unknown>
#23 0x5645f5007fdb <unknown>
#24 0x5645f5017c05 <unknown>
#25 0x7f0355d9e134 <unknown>
; 519)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/fb_videos_scraper.py", line 11, in fb_videos_scraper
    videos_scraper = AccountVideo(id)
  File "/opt/airflow/dags/utils/account_videos.py", line 22, in __init__
    super().__init__(user_id, base_url=f"https://www.facebook.com/{user_id}/videos")
  File "/opt/airflow/dags/utils/facebook_base.py", line 28, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x5645f5018a8e <unknown>
#1 0x5645f4ad5b0b <unknown>
#2 0x5645f4ac1306 <unknown>
#3 0x5645f4ac10bc <unknown>
#4 0x5645f4abf608 <unknown>
#5 0x5645f4abfab9 <unknown>
#6 0x5645f4acd160 <unknown>
#7 0x5645f4ae34ff <unknown>
#8 0x5645f4ae8a4b <unknown>
#9 0x5645f4ac002d <unknown>
#10 0x5645f4ae32f7 <unknown>
#11 0x5645f4b6acf7 <unknown>
#12 0x5645f4b499b3 <unknown>
#13 0x5645f4b13c59 <unknown>
#14 0x5645f4b14a08 <unknown>
#15 0x5645f4fe540a <unknown>
#16 0x5645f4fe885e <unknown>
#17 0x5645f4fe8308 <unknown>
#18 0x5645f4fe8ce5 <unknown>
#19 0x5645f4fceb7b <unknown>
#20 0x5645f4fe9050 <unknown>
#21 0x5645f4fb7ae9 <unknown>
#22 0x5645f5007df5 <unknown>
#23 0x5645f5007fdb <unknown>
#24 0x5645f5017c05 <unknown>
#25 0x7f0355d9e134 <unknown>

[2025-05-09T08:38:54.054+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-09T08:38:54.067+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-09T08:38:54.069+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
