[2025-05-15T02:18:44.009+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-15T02:18:44.019+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-15T02:18:42.675189 [queued]>
[2025-05-15T02:18:44.024+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-15T02:18:42.675189 [queued]>
[2025-05-15T02:18:44.024+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-15T02:18:44.033+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): tiktok_videos_scraper> on 2025-05-15 02:18:42.675197+00:00
[2025-05-15T02:18:44.035+0000] {standard_task_runner.py:72} INFO - Started process 356 to run task
[2025-05-15T02:18:44.038+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'tiktok_videos_scraper', 'manual__2025-05-15T02:18:42.675189', '--job-id', '5466', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmppv3zofvh']
[2025-05-15T02:18:44.039+0000] {standard_task_runner.py:105} INFO - Job 5466: Subtask tiktok_videos_scraper
[2025-05-15T02:18:44.074+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-15T02:18:42.675189 [running]> on host 255dbbe6d096
[2025-05-15T02:18:44.140+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='tiktok_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T02:18:42.675197+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T02:18:42.675189'
[2025-05-15T02:18:44.141+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-15T02:33:30.265+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2025-05-15T02:33:30.269+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-15T02:33:30.270+0000] {process_utils.py:132} INFO - Sending 15 to group 356. PIDs of all processes in the group: [359, 371, 378, 379, 402, 408, 449, 451, 477, 1071, 356]
[2025-05-15T02:33:30.271+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 356
[2025-05-15T02:33:30.272+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-15T02:33:30.366+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=449, status='terminated', started='02:18:44') (449) terminated with exit code None
[2025-05-15T02:33:30.367+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=402, status='terminated', started='02:18:44') (402) terminated with exit code None
[2025-05-15T02:33:30.462+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=408, status='terminated', started='02:18:44') (408) terminated with exit code None
[2025-05-15T02:33:30.464+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=451, status='terminated', started='02:18:44') (451) terminated with exit code None
[2025-05-15T02:33:30.464+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=371, status='terminated', started='02:18:43') (371) terminated with exit code None
[2025-05-15T02:33:30.465+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1071, status='terminated', started='02:21:44') (1071) terminated with exit code None
[2025-05-15T02:33:30.466+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=378, status='terminated', started='02:18:43') (378) terminated with exit code None
[2025-05-15T02:33:30.466+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=379, status='terminated', started='02:18:43') (379) terminated with exit code None
[2025-05-15T02:33:30.467+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=477, status='terminated', started='02:18:44') (477) terminated with exit code None
[2025-05-15T02:34:25.270+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=359, name='node', status='sleeping', started='02:18:43') did not respond to SIGTERM. Trying SIGKILL
[2025-05-15T02:34:25.271+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=356, name='airflow task ru', status='sleeping', started='02:18:43') did not respond to SIGTERM. Trying SIGKILL
[2025-05-15T02:34:25.271+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 356
[2025-05-15T02:34:25.279+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=359, name='node', status='terminated', started='02:18:43') (359) terminated with exit code None
[2025-05-15T02:34:25.280+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=356, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='02:18:43') (356) terminated with exit code -9
[2025-05-15T02:34:25.280+0000] {standard_task_runner.py:190} ERROR - ('Job 5466 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
