[2025-05-23T10:47:40.910+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T10:47:40.928+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-23T10:47:39.715158+00:00 [queued]>
[2025-05-23T10:47:40.934+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-23T10:47:39.715158+00:00 [queued]>
[2025-05-23T10:47:40.935+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-23T10:47:40.944+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_links_task> on 2025-05-23 10:47:39.715158+00:00
[2025-05-23T10:47:40.948+0000] {standard_task_runner.py:72} INFO - Started process 66 to run task
[2025-05-23T10:47:40.952+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'get_links_task', 'manual__2025-05-23T10:47:39.715158+00:00', '--job-id', '6706', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmpwgxjp55z']
[2025-05-23T10:47:40.953+0000] {standard_task_runner.py:105} INFO - Job 6706: Subtask get_links_task
[2025-05-23T10:47:41.015+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-23T10:47:39.715158+00:00 [running]> on host 94ec89f221a0
[2025-05-23T10:47:41.092+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='get_links_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T10:47:39.715158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T10:47:39.715158+00:00'
[2025-05-23T10:47:41.093+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-23T10:48:46.593+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-23T10:48:46.595+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-23T10:48:46.596+0000] {process_utils.py:132} INFO - Sending 15 to group 66. PIDs of all processes in the group: [69, 81, 88, 89, 117, 125, 167, 168, 202, 66]
[2025-05-23T10:48:46.596+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 66
[2025-05-23T10:48:46.596+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-23T10:48:46.604+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=168, status='terminated', started='10:47:42') (168) terminated with exit code None
[2025-05-23T10:48:46.697+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=88, status='terminated', started='10:47:41') (88) terminated with exit code None
[2025-05-23T10:48:46.698+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=202, status='terminated', started='10:47:42') (202) terminated with exit code None
[2025-05-23T10:48:46.698+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=89, status='terminated', started='10:47:41') (89) terminated with exit code None
[2025-05-23T10:48:46.698+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=81, status='terminated', started='10:47:41') (81) terminated with exit code None
[2025-05-23T10:48:46.964+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=125, status='terminated', started='10:47:42') (125) terminated with exit code None
[2025-05-23T10:48:46.965+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=117, status='terminated', started='10:47:42') (117) terminated with exit code None
[2025-05-23T10:48:46.965+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=167, status='terminated', started='10:47:42') (167) terminated with exit code None
[2025-05-23T10:49:46.598+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=69, name='node', status='sleeping', started='10:47:40') did not respond to SIGTERM. Trying SIGKILL
[2025-05-23T10:49:46.601+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=66, name='airflow task ru', status='sleeping', started='10:47:40') did not respond to SIGTERM. Trying SIGKILL
[2025-05-23T10:49:46.602+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 66
[2025-05-23T10:49:46.606+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=69, name='node', status='terminated', started='10:47:40') (69) terminated with exit code None
[2025-05-23T10:49:46.609+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=66, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='10:47:40') (66) terminated with exit code -9
[2025-05-23T10:49:46.610+0000] {standard_task_runner.py:190} ERROR - ('Job 6706 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
